version: "2"
services:
  mongo:
    restart: always
    image: mongo:3.4
    container_name: local.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /var/volume/station/mongo/configdb:/data/configdb
      - /var/volume/station/mongo/db:/data/db
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  redis:
    restart: always
    image: redis:3.2
    container_name: local.redis
    volumes:
      - /var/volume/station/redis/data:/data
  noader:
    restart: always
    image: cloudinline/noader:latest
    container_name: local.noader
    stdin_open: true
    tty: true
    depends_on:
      - mongo
      - redis
    environment:
      NOADER_PORT: "10000"
      NOADER_CONFIG: /var/volume/noader/noader.config.json
    volumes:
      - /var/volume/station/noader:/var/volume/noader
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 9999:9999/tcp
      - 10000:10000/tcp