services:
  mongo:
    container_name: mongo
    image: mongo:5.0.9
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
      - ../tmp/docker/mongo/db:/var/lib/mongodb
      - ../tmp/docker/mongo/log:/var/log/mongodb
    command: --config /etc/mongo/mongod.conf
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
  redis:
    container_name: redis
    image: redis:7.0.2
    restart: always
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8008:8081
    depends_on:
      - redis
  postgres:
    image: postgres:14.3-alpine
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        PGDATA: /var/lib/postgresql/data
    volumes:
        - ../tmp/docker/postgres/db:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: root
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_LISTEN_PORT: 8800
    ports:
        - "8800:8800"
    volumes:
        - ../tmp/docker/postgres/admin:/var/lib/pgadmin
    links:
        - "db:pgsql-server"
          