openapi: 3.0.0
info:
  title: NFT Market
  description: NFT Market API
  version: 0.0.1
servers:
  - url: "http://localhost/api/master/v0"
tags:
  - name: invoice
    description: 購物/上架/提領 訂單處理相關操作
security:
  - BaseApiKey: []
paths:
  /invoice/shopping/create:
    post:
      operationId: invoiceShoppingCreate
      tags:
        - invoice
      summary: 建立購物車交易訂單
      description: 建立購物車交易訂單
      parameters: []
      requestBody:
        description: shopping order
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                cartHash:
                  type: string
                lang:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvoiceShoppingStatus"
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  userId:
                    type: string
                  cartHash:
                    type: string
                  lang:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
  /invoice/shopping/check:
    post:
      operationId: invoiceShoppingCheck
      tags:
        - invoice
      summary: 查詢購物訂單資訊
      description: 查詢購物訂單資訊
      parameters: []
      requestBody:
        description: user check
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                invoiceId:
                  type: string
                lang:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvoiceShoppingStatus"
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  userId:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
  /cart/selling/load:
    post:
      operationId: cartSellingLoad
      tags:
        - cart
      summary: 取得上架車資訊
      description: 取得上架車資訊
      parameters: []
      requestBody:
        description: user check
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartSellingModel"
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  userId:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
  /cart/selling/save:
    post:
      operationId: cartSellingSave
      tags:
        - cart
      summary: 更新上架車資訊
      description: 更新上架車資訊
      parameters: []
      requestBody:
        description: user check
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                list:
                    type: array
                    items:
                      type: object
                      properties:
                        chainId:
                          type: integer
                        contract:
                          type: string
                        id:
                          type: integer
                        shop:
                          type: string
                wallet:
                    type: array
                    items:
                      type: object
                      properties:
                        currency:
                          type: string
                        enable:
                          type: boolean
                        rate:
                          type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CartSellingModel"
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  hash:
                    type: string
                  userId:
                    type: string
                  list:
                    type: string
                  wallet:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
  /cart/import/register:
    post:
      operationId: cartImportRegister
      tags:
        - cart
      summary: 注冊NFT匯入並取得匯入錢包賬號
      description: 注冊NFT匯入並取得匯入錢包賬號
      parameters: []
      requestBody:
        description: user check
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                chainId:
                  type: integer
                list:
                  type: array
                  items:
                    type: object
                    properties:
                      contract:
                        type: string
                        description: contract address
                      id:
                        type: integer
                        description: nft id
                importer:
                  type: string
                  description: 匯入錢包賬號
                sign:
                  type: string
                  description: eip712 簽名證明為錢包持有人
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - userId
                properties:
                  userId:
                    type: string
                  chainId:
                    type: integer
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        contract:
                          type: string
                          description: contract address
                        id:
                          type: integer
                          description: nft id
                        transfer:
                          type: string
                          description: 目標匯入賬號地址
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  chainId:
                    type: string
                  userId:
                    type: string
                  list:
                    type: string
                  importer:
                    type: string
                  sign:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
components:
  securitySchemes:
    BaseApiKey:
      type: apiKey
      name: apikey
      in: header
  schemas:
    BaseAny:
      type: object
      properties: {}
    BaseArrayAny:
      type: array
      items:
        $ref: "#/components/schemas/BaseAny"
    BaseError:
      type: object
      required:
        - code
      properties:
        code:
          description: Error code
          type: integer
        message:
          description: Error Message
          type: string
        data:
          $ref: "#/components/schemas/BaseAny"
    InvoiceShoppingStatus:
      type: object
      properties:
        userId:
          type: string
        invoiceId:
          type: string
          description: 訂單編號(ID)
        status:
          type: string
          enum:
            - success
            - fail
            - partial
            - processing
            - waiting
            - error
            - pause
        createOn:
          type: number
          description: 建立時間
        jobs:
          type: array
          items:
            type: object
            properties:
              jobType:
                type: string
                description: 換匯/鎖幣/站內購入/外站購入/結帳
              jobId:
                type: string
              data:
                type: object
              status:
                type: string
                enum:
                  - success
                  - fail
                  - partial
                  - processing
                  - waiting
                  - error
                  - pause
              finishOn:
                type: number
              description:
                type: string
    CartSellingModel:
      type: object
      properties:
        hash:
          type: string
          description: 目前資料 hash(防呆,更新時比對)
        userId:
          type: string
        list:
          type: array
          items:
            type: object
            properties:
              chainId:
                type: integer
              contract:
                type: string
              collection:
                type: string
                description: 集合名稱
              id:
                type: integer
              nftName:
                type: string
              shops:
                type: array
                items:
                  type: object
                  properties:
                    shop:
                      type: string
                    currency:
                      type: string
                    price:
                      type: number
                    enable:
                      type: boolean
        gas:
          type: array
          items:
            type: object
            properties:
              currency:
                type: string
              amount:
                type: number
        wallet:
          type: array
          items:
            type: object
            properties:
              currency:
                type: string
              balance:
                type: number
              enable:
                type: boolean
              willPay:
                type: number 
        payment:
          type: array
          items:
            type: object
            properties:
              currency:
                type: string
              amount:
                type: number
              payBy:
                type: array
                items:
                  type: object
                  properties:
                    currency:
                      type: string
                    used:
                      type: number
                    rate:
                      type: number
                    amount:
                      type: number
  responses:
    BaseAny:
      description: Response any object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseAny"
    BaseArrayAny:
      description: Response array of any
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseArrayAny"
    BaseError:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseError"
