openapi: 3.0.0
info:
  title: NFT Market
  description: NFT Market API
  version: 0.0.1
servers:
  - url: http://localhost/api/master/v0
tags: 
  - name: member
    description: 已登入使用者操作界面
security:
  - BaseApiKey: []
paths:
  /member/info:
    post:
      operationId: memberInfo
      tags:
        - member
      summary: 取得會員資訊
      description: check and renew auth token
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
      responses:
        200:
          description: 會員基本資料
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  email:
                    type: string
                  level:
                    type: integer
        401:
          description: 登入資訊錯誤
        default:
          $ref: "#/components/responses/BaseError"
  /member/verify/phone:
    post:
      operationId: memberVerifyPhone
      tags:
        - member
      summary: 送出手機驗證碼（登入中）
      description: send SMS to member phone for verify code
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                lang:
                  type: string
                  example: en-US
                  default: en-US
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                description: 成功送出並取回下次可執行時間
                type: integer
                example: 1653502991840
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  time:
                    description: 此錯誤代表尚未到達可再次送出時間
                    type: integer
                    # example: api.member.phone.verify.error.notYet
        401:
          description: 登入資訊錯誤
        default:
          $ref: "#/components/responses/BaseError"
  /member/verify/email:
    post:
      operationId: memberVerifyEmail
      tags:
        - member
      summary: 寄發電子郵件檢查碼信件（登入中）
      description: 寄發電子郵件檢查碼信件
      parameters: []
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                lang:
                  type: string
                  example: en-US
                  default: en-US
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                description: 成功送出並取回下次可執行時間
                type: integer
                example: 1653502991840
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  time:
                    description: 下次可執行時間
                    type: integer
        default:
          $ref: "#/components/responses/BaseError"
  /member/reset/phone:
    post:
      operationId: memberResetPhone
      tags:
        - member
      summary: 重設連結手機號碼
      description: 重設連結手機號碼
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
                - password
                - emailVerify
                - phone
                - phoneVerify
              properties:
                userId:
                  type: string
                password:
                  type: string
                emailVerify:
                  type: string
                  description: email 驗證碼
                phone:
                  type: string
                  description: 新手機號碼
                phoneVerify:
                  type: string
                  description: 使用 guestVerifyPhone 送出之手機驗證碼
      responses:
        200:
          description: OK --> renew token salt(logout all devices)
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  emailVerify:
                    type: string
                    example: api.member.reset.phone.error.emailVerify.notMatch
                  phone:
                    type: string
                    example: api.member.reset.phone.error.phone.exist
                  phoneVerify:
                    type: string
                    example: api.member.reset.phone.error.phoneVerify.notMatch
                  password:
                    type: string
                    example: api.member.reset.phone.error.password.notMatch
        401:
          description: 登入資訊錯誤
        default:
          $ref: "#/components/responses/BaseError"
  /member/reset/password:
    post:
      operationId: memberResetPassword
      tags:
        - member
      summary: 重設登入密碼
      description: Reset member password
      parameters: []
      requestBody:
        description: Reset informations
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
                - emailVerify
                - phoneVerify
                - password
              properties:
                userId:
                  type: string
                emailVerify:
                  type: string
                phoneVerify:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: OK --> renew token salt(logout all devices)
        403:
          description: 注冊資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  email:
                    type: string
                    example: api.member.reset.password.error.email.format
                  emailVerify:
                    type: string
                    example: api.member.reset.password.error.emailVerify.notMatch
                  phoneVerify:
                    type: string
                    example: api.member.reset.password.error.phoneVerify.overTime
                  password:
                    type: string
                    example: api.member.reset.password.error.password.minLength8
        default:
          $ref: "#/components/responses/BaseError"
components:
  securitySchemes:
    BaseApiKey:
      type: apiKey
      name: apikey
      in: header
  schemas:
    BaseAny:
      type: object
      properties: {}
    BaseArrayAny:
      type: array
      items:
        $ref: "#/components/schemas/BaseAny"
    BaseError:
      type: object
      required:
        - code
      properties:
        code:
          description: Error code
          type: integer
        message:
          description: Error Message
          type: string
        data:
          $ref: "#/components/schemas/BaseAny"
  responses:
    BaseError:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseError"
