openapi: 3.0.0
info:
  title: NFT Market
  description: NFT Market API
  version: 0.0.1
servers:
  - url: "http://localhost/api/master/v0"
tags:
  - name: mint
    description: NFT 代客鑄造設定界面
paths:
  /mint/list:
    post:
      operationId: mintList
      tags:
        - mint
      summary: 列出代鑄專案清單
      description: mint list
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                offset:
                  type: integer
                limit:
                  type: integer
                filter:
                  type: object
                  properties:
                    status:
                      type: string
                    createAfter:
                      type: integer
                    createBefore:
                      type: integer
                    chainId:
                      type: integer
                    category:
                      type: string
                    mints:
                      type: array
                      items:
                        type: string
                        description: filter by mintId
                sort:
                  type: array
                  items:
                    type: object
                    properties:
                      field:
                        type: string
                      mode:
                        type: string
                        enum:
                          - asc
                          - des
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: |-
                  NFT 系列回傳物件
                properties:
                  total:
                    type: integer
                    description: 查詢結果總數
                  offset:
                    type: integer
                    description: 回傳起始位置
                  list:
                    type: array
                    items:
                      $ref: "#/components/schemas/MintSummaryModel"
        # 401:
        #   description: 登入資訊錯誤
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  filter:
                    type: string
                    description: ...
                  sort:
                    type: string
                    description: ...
        default:
          $ref: "#/components/responses/BaseError"
  /mint/read:
    post:
      operationId: mintRead
      # security:
      #   - BaseApiKey: []
      tags:
        - mint
      summary: 取得專案資訊
      description: mint list
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                mintId:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MintDetailModel"
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  userId:
                    type: string
                    description: ...
                  mintId:
                    type: string
                    description: ...
        default:
          $ref: "#/components/responses/BaseError"
  /mint/create:
    post:
      operationId: mintCreate
      security:
        - BaseApiKey: []
      tags:
        - mint
      summary: 建立專案
      description: mint create
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                detail:
                  $ref: "#/components/schemas/MintDetailModel"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MintDetailModel"
        401:
          description: 登入資訊錯誤
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  hash:
                    type: string
                  detail:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
  /mint/update:
    post:
      operationId: mintUpdate
      security:
        - BaseApiKey: []
      tags:
        - mint
      summary: 更新專案
      description: mint update
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                hash:
                  type: string
                detail:
                  $ref: "#/components/schemas/MintDetailModel"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MintDetailModel"
        401:
          description: 登入資訊錯誤
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  hash:
                    type: string
                  detail:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
  /mint/delete:
    post:
      operationId: mintDelete
      security:
        - BaseApiKey: []
      tags:
        - mint
      summary: 刪除專案
      description: mint delete
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                mintId:
                  type: string
                mintHash:
                  type: string
      responses:
        200:
          description: OK
        401:
          description: 登入資訊錯誤
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  mintId:
                    type: string
                  mintHash:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
  /mint/action:
    post:
      operationId: mintAction
      security:
        - BaseApiKey: []
      tags:
        - mint
      summary: 設定專案狀態 啓用/停用/上架/下架/送審/測試
      description: mint action
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                mintId:
                  type: string
                hash:
                  type: string
                action:
                  type: string
                  description: 啓用 / 停用 / 上架 / 下架 / 送審 / 測試
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MintDetailModel"
        401:
          description: 登入資訊錯誤
        403:
          description: 資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  mintId:
                    type: string
                  hash:
                    type: string
                  action:
                    type: string
        default:
          $ref: "#/components/responses/BaseError"
components:
  securitySchemes:
    BaseApiKey:
      type: apiKey
      name: apikey
      in: header
  schemas:
    MintSummaryModel:
      type: object
      properties:
        id:
          type: string
        hash:
          type: string
        createOn:
          type: integer
        banner:
          type: string
          description: 大圖連結
        image:
          type: string
          description: 小圖/NFT示意圖連結
        status:
          type: string
        title:
          type: string
        mintOn:
          type: integer
        currency:
          type: string
        price:
          type: number
        totalMints:
          type: integer
          description: 站内 mint 總次數
        totalSupply:
          type: integer
          description: 合約總供應量
        totalMinted:
          type: integer
          description: 合約已 mint 總數量
    MintDetailModel:
      type: object
      properties:
        id:
          type: string
        hash:
          type: string
        createOn:
          type: integer
        isLock:
          type: boolean
          description: 是否已鎖定
        isPublish:
          type: boolean
          description: 是否已上架(可查詢)
        editable:
          type: boolean
          description: 是否可編輯，伺服器視狀態給予值
        mintOn:
          type: integer
          description: 合約可執行鑄造時間
        banner:
          type: string
          description: 大圖連結
        image:
          type: string
          description: 小圖/NFT示意圖連結
        description:
          type: string
          description: 項目及鑄造説明文字
        homepage:
          type: string
          description: 官方網站連結
        communities:
          type: array
          items:
            type: object
            properties:
              platform:
                type: string
                description: discord / facebook / twitter / github / telgram / instegram
              url:
                type: string
        status:
          type: string
        title:
          type: string
        currency:
          type: string
        price:
          type: number
          description: 單價
        collection:
          type: string
          description: NFT 集合名稱
        chainId:
          type: integer
        contract:
          type: string
          description: NFT 合約地址
        function:
          type: string
          description: 呼叫合約函數名稱
        argument:
          type: object
          description: 呼叫合約參數(鑄造數量)
          properties:
            fix:
              type: integer
            min:
              type: integer
            max:
              type: integer
        expected:
          type: integer
          description: 預期收到NFT數量(不參與計算,在無argument情況下,顯示)
    BaseAny:
      type: object
      properties: {}
    BaseArrayAny:
      type: array
      items:
        $ref: "#/components/schemas/BaseAny"
    BaseError:
      type: object
      required:
        - code
      properties:
        code:
          description: Error code
          type: integer
        message:
          description: Error Message
          type: string
        data:
          $ref: "#/components/schemas/BaseAny"
  responses:
    BaseAny:
      description: Response any object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseAny"
    BaseArrayAny:
      description: Response array of any
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseArrayAny"
    BaseError:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseError"
