openapi: 3.0.0
info:
  title: NFT Market
  description: NFT Market API
  version: 0.0.1
servers:
  - url: http://localhost/api/master/v0
tags: 
  - name: wallet
    description: 使用者錢包操作
security:
  - BaseApiKey: []
paths:
  /wallet/balance:
    post:
      operationId: walletBalance
      tags:
        - wallet
      summary: 取得錢包可用餘額
      description: wallet balance
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              properties:
                userId:
                  type: string
              required:
                - userId
      responses:
        200:
          description: 錢包餘額
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    currency:
                      type: string
                      description: 虛擬貨幣名稱
                      example: ETH
                    symbol:
                      type: string
                      description: 貨幣標識符
                      example: Ξ
                    decimal:
                      type: integer
                      description: 小數位數
                      example: 4
                    balance:
                      description: 可動用餘額
                      type: number
                    lock:
                      description: 鎖倉金額
                      type: number
        401:
          description: 登入資訊錯誤
        default:
          $ref: "#/components/responses/BaseError"
  /wallet/history:
    post:
      operationId: walletHistory
      tags:
        - wallet
      summary: 分頁拉取用戶存提幣記錄
      description: 分頁拉取用戶存提幣記錄
      parameters: []
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                offset:
                  type: integer
                  description: 起始資料位置索引(0 base)
                  default: 0
                limit:
                  type: integer
                  description: 每頁個數
                  default: 20
      responses:
        200:
          description: 錢包存提紀錄
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        time:
                          type: number
                          description: 建立時間
                        currency:
                          type: string
                          description: 虛擬貨幣名稱
                          example: ETH
                        symbol:
                          type: string
                          description: 貨幣標識符
                          example: Ξ
                        decimal:
                          type: integer
                          description: 顯示小數位數
                          example: 4
                        from:
                          type: string
                          description: 出金賬號
                        into:
                          type: string
                          description: 入金賬號
                        chainId:
                          type: string
                          description: |
                            [交易公鏈 ID](https://chainlist.org/)
                            1 for Ethereum Mainnet
                          example: 1
                        txn:
                          type: string
                          description: 鏈上交易序號
                        # memo:
                        #   type: string
                        #   description: 鏈上交易備注(BNB maninnet)
                        direction:
                          type: string
                          enum:
                            - diposit
                            - withdraw
                        amount:
                          description: 交易數量
                          type: number
                        status:
                          type: string
                          enum:
                            - success
                            - cancel
                            - processing
                            - waiting
        401:
          description: 登入資訊錯誤
        default:
          $ref: "#/components/responses/BaseError"
  /wallet/diposit/info:
    post:
      operationId: walletDipositInfo
      tags:
        - wallet
      summary: 取得虛擬貨幣入金賬號
      description: 取得虛擬貨幣入金賬號
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
                - currency
              properties:
                userId:
                  type: string
                currency:
                  type: string
                  description: 虛擬貨幣名稱
                  example: ETH
      responses:
        200:
          description: 入金賬號
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - symbol
                    - chainId
                    - address
                  properties:
                    currency:
                      type: string
                      description: 虛擬貨幣名稱
                      example: ETH
                    # symbol:
                    #   type: string
                    #   description: 貨幣標識符
                    #   example: Ξ
                    token:
                      type: string
                      description: 虛擬貨幣合約地址(ex4:USDT on ether)
                      example: 0xdAC17F958D2ee523a2206206994597C13D831xxx
                    chainId:
                      type: string
                      description: |
                        [匯款公鏈 ID](https://chainlist.org/)
                        1 for Ethereum Mainnet
                      example: 1
                    address:
                      type: string
                      description: 匯入賬號/空為目前無可用賬號
                    memo:
                      description: 匯款注記(BNB Mainnet)
                      type: string
                    effect:
                      description: 有效期限(timestamp)/0為無限期有效(=固定賬號)
                      type: number
                      example: 1653631833378
        401:
          description: 登入資訊錯誤
        default:
          $ref: "#/components/responses/BaseError"
  /wallet/withdraw/info:
    post:
      operationId: walletWithdrawInfo
      tags:
        - wallet
      summary: 取得虛擬貨幣出金方式
      description: 取得虛擬貨幣出金方式
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
                - currency
              properties:
                userId:
                  type: string
                currency:
                  type: string
                  description: 虛擬貨幣名稱
                  example: ETH
      responses:
        200:
          description: 出金管道
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - currency
                    - chainId
                    - address
                  properties:
                    currency:
                      type: string
                      description: 虛擬貨幣名稱
                      example: ETH
                    symbol:
                      type: string
                      description: 貨幣標識符
                      example: Ξ
                    token:
                      type: string
                      description: 虛擬貨幣合約地址(ex4:USDT on ether)
                      example: 0xdAC17F958D2ee523a2206206994597C13D831xxx
                    chainId:
                      type: string
                      description: |
                        [匯款公鏈 ID](https://chainlist.org/)
                        1 for Ethereum Mainnet
                      example: 1
                    min:
                      type: number
                      description: 最小轉出數量
                    max:
                      type: number
                      description: 目前可用最大轉出數量(包含會員等級限制)
                    fee:
                      type: number
                      description: 轉出手續費(同幣別内扣)
                    # memo:
                    #   description: 匯款注記(BNB Mainnet)
                    #   type: string
        401:
          description: 登入資訊錯誤
        default:
          $ref: "#/components/responses/BaseError"
  /wallet/withdraw/submit:
    post:
      operationId: walletWithdrawSubmit
      tags:
        - wallet
      summary: 確認虛擬貨幣出金
      description: 確認虛擬貨幣出金
      parameters: []
      requestBody:
        description: user id
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - userId
                - currency
                - chainId
                - amount
                - address
                - phoneVerify
              properties:
                userId:
                  type: string
                currency:
                  type: string
                  description: 虛擬貨幣名稱
                  example: ETH
                chainId:
                  type: string
                  description: |
                    [匯款公鏈 ID](https://chainlist.org/)
                    1 for Ethereum Mainnet
                  example: 1
                amount:
                  type: number
                address:
                  type: string
                phoneVerify:
                  description: 手機驗證碼
                  type: string
      responses:
        200:
          description: OK
        401:
          description: 登入資訊錯誤
        403:
          description: 提領資訊錯誤
          content:
            application/json:
              schema:
                description: 回傳對應欄位的錯誤訊息/代號
                type: object
                properties:
                  currency:
                    type: string
                    example: api.wallet.withdraw.submit.error.currency.notExist
                  chainId:
                    type: string
                    example: api.wallet.withdraw.submit.error.chainId.notExist
                  amount:
                    type: string
                    example: api.wallet.withdraw.submit.error.amount.overMax
                  address:
                    type: string
                    example: api.wallet.withdraw.submit.error.address.format
                  phoneVerify:
                    type: string
                    example: api.wallet.withdraw.submit.error.phoneVerify.notMatch
        default:
          $ref: "#/components/responses/BaseError"
components:
  securitySchemes:
    BaseApiKey:
      type: apiKey
      name: apikey
      in: header
  schemas:
    BaseAny:
      type: object
      properties: {}
    BaseArrayAny:
      type: array
      items:
        $ref: "#/components/schemas/BaseAny"
    BaseError:
      type: object
      required:
        - code
      properties:
        code:
          description: Error code
          type: integer
        message:
          description: Error Message
          type: string
        data:
          $ref: "#/components/schemas/BaseAny"
  responses:
    BaseError:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseError"
